website
Orles/react-stellar-burger pull request #3
Opened 2023-09-04 07:23 UTC by Orles

2023-09-04 08:13 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Настроены все редиректы
- Есть автологин
- Реализовали обновление токена

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если поменять какие-то данные в профиле, но не трогать пароль, то он всё равно попадает в запрос в виде `*******`. Т.е. у юзера неявно меняется пароль.

<img width="520" alt="Снимок экрана 2023-09-04 в 11 02 07" src="https://github.com/Orles/react-stellar-burger/assets/60173362/852de352-f723-468f-9f8e-9416957f7270">

- на тег form нужно навешивать обработчик onSubmit, а не обработчик onClick на кнопку сабмита.
- Обновление токена должно происходить так же и при изменении данных юзера

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-04 08:13 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +    const { burgerIngridients } = useSelector(state => state.burgerIngridients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-09-04 08:13 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <Route path="/ingredients/:id" element={<IngredientDetailsPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-09-04 08:13 UTC, andryxxa93 commented on src/utils/Api.js
> +export function registerUser(name, email, password) {
**Можно лучше**
У вас сейчас смешаны запросы и обработка экшенов. Желательно отделить одно от другого. Т.е. в данном файле должны остаться только тело запросов, а диспатчи экшенов должны быть в самих компонентах или файле `actions`

2023-09-04 08:13 UTC, andryxxa93 commented on src/components/app/app.jsx
> +)
**Можно лучше**
Использовать такие переменные как `ok` - не стоит, по ним невозможно сказать за что они отвечают. Так же данный navigate должен быть внутри страницы `forgot-password`

2023-09-04 20:31 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-15 10:02 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации, так как нужно прислать ссылку на **открытый** пулл-реквест с кодом данного этапа, а не уже проверенного в прошлый раз

2023-09-15 11:09 UTC, merged